# ─────────────────────────────────────────────────────────────────────────────
# Site Settings
# ─────────────────────────────────────────────────────────────────────────────

title:       "Biaohang Yuan (袁彪航)"
description: "I am interested in AI interpretability and AI safety."
repository:  "gugu11riji/BiaohangYuan.github.io"   # “owner/repo” 格式，去掉 https:// 前缀

google_scholar_stats_use_cdn: true

# ─────────────────────────────────────────────────────────────────────────────
# Google Analytics
# ─────────────────────────────────────────────────────────────────────────────

google_analytics_id: "G-SWFCX99KQZ"              # 放在引号里更保险

# ─────────────────────────────────────────────────────────────────────────────
# SEO Related
# ─────────────────────────────────────────────────────────────────────────────

google_site_verification: "b_BbOIt7d513ZXYDw-YRMicO6O5tthYiouqWDdWjGTU"
bing_site_verification:   "B5AA590E7B9C03956A6F7DEC0F776211"
baidu_site_verification:  "code-ZxFK3f4pfb"

# ─────────────────────────────────────────────────────────────────────────────
# Site Author
# ─────────────────────────────────────────────────────────────────────────────

author:
  name:          "Biaohang Yuan (袁彪航)"
  avatar:        "images/personal.jpg"
  bio:           ""
  location:      "Singapore"
  employer:      ""
  pubmed:        ""
  googlescholar: "https://scholar.google.com/citations?user=4FA6C0AAAAAJ"
  email:         "GuloveLY@outlook.com"
  researchgate:  ""
  uri:           ""
  bitbucket:     ""
  codepen:       ""
  dribbble:      ""
  flickr:        ""
  facebook:      ""
  foursquare:    ""
  github:        "gugu11riji"   # 填你的 GitHub 用户名
  google_plus:   ""
  keybase:       ""
  instagram:     ""
  impactstory:   ""
  lastfm:        ""
  linkedin:      "rayeren"
  dblp:          "https://dblp.org/pid/75/6568-6.html"
  orcid:         "https://orcid.org/0000-0002-9160-3848"
  pinterest:     ""
  soundcloud:    ""
  stackoverflow: ""
  steam:         ""
  tumblr:        ""
  twitter:       ""
  vine:          ""
  weibo:         ""
  xing:          ""
  youtube:       ""
  wikipedia:     ""

# ─────────────────────────────────────────────────────────────────────────────
# Include / Exclude / Keep
# ─────────────────────────────────────────────────────────────────────────────

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - google_scholar_crawler
  - github_myprofile_updater

keep_files:
  - .git
  - .svn

# ─────────────────────────────────────────────────────────────────────────────
# Encoding & Markdown
# ─────────────────────────────────────────────────────────────────────────────

encoding:    "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input:          GFM
  hard_wrap:      false
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# ─────────────────────────────────────────────────────────────────────────────
# Defaults
# ─────────────────────────────────────────────────────────────────────────────

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout:         default
      author_profile: true

# ─────────────────────────────────────────────────────────────────────────────
# Sass/SCSS
# ─────────────────────────────────────────────────────────────────────────────

sass:
  sass_dir: _sass
  style:    compressed

# ─────────────────────────────────────────────────────────────────────────────
# Outputting
# ─────────────────────────────────────────────────────────────────────────────

permalink:  /:categories/:title/
timezone:   Asia/Shanghai

# ─────────────────────────────────────────────────────────────────────────────
# Plugins (GitHub Pages 支持列表)
# ─────────────────────────────────────────────────────────────────────────────

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# ─────────────────────────────────────────────────────────────────────────────
# HTML Compression (可选)
# ─────────────────────────────────────────────────────────────────────────────

compress_html:
  clippings: all
  ignore:
    envs: development

